#!/bin/sh

# CM211-1-ZG single-port bypass-router defaults.
uci -q batch <<'EOF'
set system.@system[0].hostname='CM211-OpenWrt'
set system.@system[0].timezone='CST-8'
set system.@system[0].zonename='Asia/Shanghai'

set network.lan.proto='static'
set network.lan.ipaddr='192.168.1.2'
set network.lan.netmask='255.255.255.0'
set network.lan.gateway='192.168.1.1'
delete network.lan.dns
add_list network.lan.dns='192.168.1.1'
set network.lan.delegate='0'

set dhcp.lan.ignore='1'
set dhcp.lan.dhcpv6='disabled'
set dhcp.lan.ra='disabled'
set dhcp.lan.ndp='disabled'

set firewall.@zone[0].input='ACCEPT'
set firewall.@zone[0].output='ACCEPT'
set firewall.@zone[0].forward='ACCEPT'
EOF

uci commit system
uci commit network
uci commit dhcp
uci commit firewall

cat > /etc/sysctl.d/99-cm211-bypass.conf <<'EOF'
net.ipv4.ip_forward=1
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
EOF

exit 0
